import type { CategoryRecord } from "../types";

export const DEFAULT_CATEGORIES: Omit<CategoryRecord, "createdAt">[] = [
  // Income Categories
  {
    id: "luong",
    name: "Lương",
    icon: "Banknote",
    color: "#22c55e",
    type: "income",
    isDefault: true,
  },
  {
    id: "thuong",
    name: "Thưởng",
    icon: "Gift",
    color: "#16a34a",
    type: "income",
    isDefault: true,
  },
  {
    id: "dau-tu",
    name: "Đầu tư",
    icon: "TrendingUp",
    color: "#15803d",
    type: "income",
    isDefault: true,
  },
  {
    id: "kinh-doanh",
    name: "Kinh doanh",
    icon: "Building2",
    color: "#059669",
    type: "income",
    isDefault: true,
  },
  {
    id: "freelance",
    name: "Freelance",
    icon: "Laptop",
    color: "#0d9488",
    type: "income",
    isDefault: true,
  },
  {
    id: "ban-hang",
    name: "Bán hàng",
    icon: "ShoppingCart",
    color: "#0891b2",
    type: "income",
    isDefault: true,
  },
  {
    id: "cho-thue",
    name: "Cho thuê",
    icon: "Home",
    color: "#0284c7",
    type: "income",
    isDefault: true,
  },
  {
    id: "lai-suat",
    name: "Lãi suất",
    icon: "PiggyBank",
    color: "#2563eb",
    type: "income",
    isDefault: true,
  },
  {
    id: "thu-nhap-khac",
    name: "Thu nhập khác",
    icon: "Plus",
    color: "#4338ca",
    type: "income",
    isDefault: true,
  },
  // Expense Categories
  {
    id: "an-uong",
    name: "Ăn uống",
    icon: "UtensilsCrossed",
    color: "#ef4444",
    type: "expense",
    budget: 2000000, // 2 triệu VND
    isDefault: true,
  },
  {
    id: "di-chuyen",
    name: "Di chuyển",
    icon: "Car",
    color: "#3b82f6",
    type: "expense",
    budget: 1500000, // 1.5 triệu VND
    isDefault: true,
  },
  {
    id: "mua-sam",
    name: "Mua sắm",
    icon: "ShoppingBag",
    color: "#8b5cf6",
    type: "expense",
    budget: 3000000, // 3 triệu VND
    isDefault: true,
  },
  {
    id: "giai-tri",
    name: "Giải trí",
    icon: "Gamepad2",
    color: "#f59e0b",
    type: "expense",
    budget: 1000000, // 1 triệu VND
    isDefault: true,
  },
  {
    id: "hoa-don",
    name: "Hóa đơn & Tiện ích",
    icon: "Zap",
    color: "#10b981",
    type: "expense",
    budget: 1500000, // 1.5 triệu VND
    isDefault: true,
  },
  {
    id: "suc-khoe",
    name: "Sức khỏe",
    icon: "Heart",
    color: "#f97316",
    type: "expense",
    budget: 1000000, // 1 triệu VND
    isDefault: true,
  },
  {
    id: "giao-duc",
    name: "Giáo dục",
    icon: "GraduationCap",
    color: "#6366f1",
    type: "expense",
    budget: 2000000, // 2 triệu VND
    isDefault: true,
  },
  {
    id: "du-lich",
    name: "Du lịch",
    icon: "Plane",
    color: "#14b8a6",
    type: "expense",
    budget: 5000000, // 5 triệu VND
    isDefault: true,
  },
  {
    id: "dich-vu",
    name: "Dịch vụ & Đăng ký",
    icon: "CreditCard",
    color: "#8b5cf6",
    type: "expense",
    budget: 500000, // 500k VND
    isDefault: true,
  },
  {
    id: "con-cai",
    name: "Con cái",
    icon: "Baby",
    color: "#f472b6",
    type: "expense",
    budget: 3000000, // 3 triệu VND
    isDefault: true,
  },
  {
    id: "gia-dinh",
    name: "Gia đình",
    icon: "Users",
    color: "#f43f5e",
    type: "expense",
    budget: 3000000, // 3 triệu VND
    isDefault: true,
  },
  {
    id: "khac",
    name: "Khác",
    icon: "MoreHorizontal",
    color: "#6b7280",
    type: "both",
    budget: 1000000, // 1 triệu VND
    isDefault: true,
  },
];

export const CATEGORY_KEYWORDS = {
  // Income Keywords
  luong: [
    "lương",
    "salary",
    "pay",
    "wage",
    "tiền lương",
    "phát lương",
    "monthly salary",
    "lương tháng",
    "lương cơ bản",
    "basic salary",
  ],
  thuong: [
    "thưởng",
    "bonus",
    "incentive",
    "commission",
    "hoa hồng",
    "thưởng tết",
    "thưởng cuối năm",
    "year end bonus",
    "quarterly bonus",
    "thưởng quý",
  ],
  "dau-tu": [
    "đầu tư",
    "investment",
    "lãi cổ phiếu",
    "dividend",
    "stock profit",
    "crypto",
    "bitcoin",
    "forex",
    "fund",
    "mutual fund",
    "lãi suất",
    "interest",
  ],
  "kinh-doanh": [
    "kinh doanh",
    "business",
    "doanh thu",
    "revenue",
    "profit",
    "lợi nhuận",
    "buôn bán",
    "kiếm được",
    "thu về",
    "bán hàng",
  ],
  freelance: [
    "freelance",
    "part time",
    "làm thêm",
    "side job",
    "consulting",
    "tư vấn",
    "project",
    "dự án",
    "contract",
    "hợp đồng",
    "remote work",
  ],
  "ban-hang": [
    "bán",
    "sale",
    "sold",
    "bán hàng",
    "retail",
    "online selling",
    "shopee bán",
    "lazada bán",
    "facebook bán",
    "marketplace",
  ],
  "cho-thue": [
    "cho thuê",
    "rent",
    "rental",
    "thuê nhà",
    "thuê phòng",
    "cho thuê xe",
    "airbnb",
    "homestay",
  ],
  "lai-suat": [
    "lãi",
    "interest",
    "lãi suất",
    "ngân hàng",
    "tiết kiệm",
    "savings",
    "gửi tiết kiệm",
    "term deposit",
  ],
  "thu-nhap-khac": [
    "thu nhập khác",
    "other income",
    "miscellaneous income",
    "refund",
    "hoàn tiền",
    "cashback",
    "reward",
    "thưởng",
    "prize",
  ],
  // Expense Keywords
  "an-uong": [
    "ăn",
    "uống",
    "cơm",
    "phở",
    "bún",
    "miến",
    "bánh",
    "chè",
    "trà",
    "cà phê",
    "nhà hàng",
    "quán",
    "buffet",
    "lẩu",
    "nướng",
    "chợ",
    "siêu thị",
    "thức ăn",
    "bữa sáng",
    "bữa trưa",
    "bữa tối",
    "bia",
    "rượu",
    "nước",
    "sữa",
    "kẹo",
    "snack",
    "fastfood",
    "mcdonald",
    "kfc",
    "lotteria",
    "pizza",
    "gà rán",
    "tạp hóa",
    "chợ",
    "vinmart",
    "coopmart",
    "big c",
    "lotte mart",
  ],
  "di-chuyen": [
    "xe",
    "taxi",
    "grab",
    "uber",
    "be",
    "gojek",
    "xăng",
    "dầu",
    "xe máy",
    "ô tô",
    "xe bus",
    "xe khách",
    "tàu",
    "máy bay",
    "vé",
    "cước",
    "phí",
    "bảo dưỡng",
    "sửa chữa",
    "gửi xe",
    "đỗ xe",
    "cầu đường",
    "phí đường",
    "vietjet",
    "bamboo",
    "vietnam airline",
    "grab bike",
    "grab car",
    "xe ôm",
    "cyclo",
    "xích lô",
    "metro",
    "bus",
    "bến xe",
  ],
  "mua-sam": [
    "mua",
    "shopping",
    "quần áo",
    "giày",
    "túi",
    "đồng hồ",
    "trang sức",
    "điện tử",
    "điện thoại",
    "laptop",
    "máy tính",
    "tv",
    "tivi",
    "nội thất",
    "đồ gia dụng",
    "mỹ phẩm",
    "chăm sóc",
    "mall",
    "trung tâm",
    "cửa hàng",
    "vincom",
    "aeon",
    "diamond plaza",
    "saigon centre",
    "takashimaya",
    "shopee",
    "lazada",
    "tiki",
    "sendo",
    "online",
    "ship",
    "giao hàng",
  ],
  "giai-tri": [
    "phim",
    "rạp",
    "cinema",
    "cgv",
    "lotte",
    "galaxy",
    "concert",
    "show",
    "ca nhạc",
    "karaoke",
    "bar",
    "pub",
    "club",
    "game",
    "net",
    "bi-a",
    "bowling",
    "massage",
    "spa",
    "gym",
    "thể thao",
    "bóng đá",
    "cầu lông",
    "bơi lội",
    "du lịch",
    "picnic",
    "cafe",
    "trà sữa",
    "bia ôm",
    "nhậu",
  ],
  "hoa-don": [
    "điện",
    "nước",
    "gas",
    "internet",
    "wifi",
    "điện thoại",
    "truyền hình",
    "cáp",
    "viettel",
    "mobifone",
    "vinaphone",
    "vnpt",
    "fpt",
    "sài gòn tourist",
    "evn",
    "sawaco",
    "hóa đơn",
    "cước",
    "phí",
    "dịch vụ",
    "monthly",
    "hàng tháng",
  ],
  "suc-khoe": [
    "bác sĩ",
    "doctor",
    "bệnh viện",
    "phòng khám",
    "thuốc",
    "pharmacy",
    "nhà thuốc",
    "khám",
    "chữa",
    "răng",
    "nha khoa",
    "mắt",
    "tim",
    "xét nghiệm",
    "chích ngừa",
    "bảo hiểm",
    "y tế",
    "sức khỏe",
    "vitamin",
    "thuốc bổ",
    "massage",
    "spa",
    "vinmec",
    "fv",
    "ung bướu",
    "đa khoa",
    "chuyên khoa",
  ],
  "giao-duc": [
    "học",
    "trường",
    "đại học",
    "cao đẳng",
    "trung học",
    "tiểu học",
    "mầm non",
    "học phí",
    "sách",
    "vở",
    "bút",
    "đồ dùng",
    "khóa học",
    "lớp",
    "gia sư",
    "tiếng anh",
    "toán",
    "văn",
    "lý",
    "hóa",
    "sinh",
    "sử",
    "địa",
    "ngoại ngữ",
    "kỹ năng",
    "chứng chỉ",
    "bằng cấp",
    "thi",
    "kiểm tra",
  ],
  "du-lich": [
    "du lịch",
    "travel",
    "khách sạn",
    "hotel",
    "resort",
    "homestay",
    "airbnb",
    "vé máy bay",
    "tour",
    "guide",
    "hướng dẫn",
    "visa",
    "hộ chiếu",
    "vali",
    "đặt phòng",
    "booking",
    "agoda",
    "đà lạt",
    "nha trang",
    "phú quốc",
    "hạ long",
    "sapa",
    "hội an",
    "huế",
    "vũng tàu",
    "mũi né",
    "cần thơ",
  ],
  "dich-vu": [
    "netflix",
    "spotify",
    "youtube",
    "facebook",
    "google",
    "apple",
    "microsoft",
    "office",
    "adobe",
    "zoom",
    "skype",
    "dropbox",
    "icloud",
    "drive",
    "đăng ký",
    "subscription",
    "monthly",
    "annual",
    "hàng tháng",
    "hàng năm",
    "premium",
    "pro",
    "plus",
    "membership",
    "thành viên",
    "gói cước",
  ],
  "con-cai": [
    "con",
    "cái",
    "bé",
    "trẻ em",
    "em bé",
    "sữa bột",
    "tã",
    "đồ chơi",
    "quần áo trẻ em",
    "sách thiếu nhi",
    "vaccin",
    "tiêm chủng",
    "khám bệnh cho bé",
    "học phí mầm non",
    "học phí",
    "đồ dùng học tập",
    "bánh kẹo",
    "sữa tươi",
    "váy bé gái",
    "quần bé trai",
    "giày trẻ em",
    "cặp sách",
    "xe đẩy",
    "nôi",
    "ghế ăn dặm",
    "bình sữa",
    "núm ty",
    "kem đánh răng trẻ em",
    "dầu tắm bé",
    "phấn rôm",
  ],
  "gia-dinh": [
    "cha mẹ",
    "bố mẹ",
    "gia đình",
    "family support",
    "gửi tiền",
    "chuyển khoản",
    "ck",
    "support",
    "hỗ trợ",
    "chu cấp",
    "nuôi",
    "phụng dưỡng",
    "mẹ",
    "bố",
    "cha",
    "anh",
    "chị",
    "em",
    "vợ",
    "chồng",
    "con",
    "cháu",
    "ông",
    "bà",
  ],
  khac: [
    "khác",
    "other",
    "misc",
    "linh tinh",
    "tạp",
    "phí",
    "fee",
    "charge",
    "thuế",
    "tax",
    "phạt",
    "fine",
    "tips",
    "bo",
    "từ thiện",
    "charity",
    "quà",
    "gift",
    "biếu",
    "tặng",
    "vay",
    "trả nợ",
    "lãi",
    "gửi tiết kiệm",
  ],
};
